name: SkyWarsFFA
version: '${project.version}'
main: de.maifii.skywarsffa.SkyWarsFFA
api-version: 1.18
authors: [ MaifiiDE, Wawwior ]

commands:
  mycommand:

  build:


libraries: [
  "com.mojang:brigadier:1.0.18"
]
