name: SkyWarsFFA
version: '${project.version}'
main: de.maifii.skywarsffa.SkyWarsFFA
api-version: 1.18
authors: [ MaifiiDE, Wawwior ]

commands:
  set:
    description: Setzt eine Location.
  build:
    description: Setzt dich in den Bau Modus.
